# SPDX-FileCopyrightText: Magenta ApS
# SPDX-License-Identifier: MPL-2.0
---
# https://kopf.readthedocs.io/en/stable/deployment/
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "konserver.serviceAccountName" . }}
  labels:
    {{ include "konserver.labels" . | nindent 4 }}
rules:
  # Kopf Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
  # Kopf Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # Application: manipulation of watched resources
  {{- range .Values.watchedResources }}
  - apiGroups: ["{{ .group  }}"]
    resources: ["{{ .name  }}"]
    verbs: [list, watch, patch]
  {{- end }}
{{- end }}
