# SPDX-FileCopyrightText: Magenta ApS
# SPDX-License-Identifier: MPL-2.0
---
# https://kopf.readthedocs.io/en/stable/deployment/
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "konserver.serviceAccountName" . }}
  labels:
  {{- include "konserver.labels" . | nindent 4 }}
{{- end }}
